### ISSUE TITLE
Can we get a column for "duration?"

### ISSUE THREAD

**Issue by Fofer** [fflewddur/archivo#47]
So we know how long the recordings are :)

**Comment by fflewddur** [comment]
This is already available in the information section at the bottom of the window :)

**Comment by Fofer** [comment]
Ah yes, I see it there now.  Thanks :)

A column would be easier to browse/glance though, as it would also be sortable.

**Comment by fflewddur** [comment]
Good point; I'll target this for the 1.1 release.
