### ISSUE TITLE
Crashes upon first opening app after install

### ISSUE THREAD

**Issue by alienmeatsack** [fflewddur/archivo#51]
"Archivo quit unexpectedly" error. Clicking Reopen results in same crash.
App is freshly installed (drag and drop) from the latest beta 1.0 B2
iMac 27" Late 2013
3.4 GHz i5
16GB RAM
Fusion Drive
El Capitan 10.11.3

Let me know what other logs you want or need to check into this, I'll be happy to help.

Crash log attached.
[Archivo 1.0B2 Crash Log 02102016.txt](https://github.com/fflewddur/archivo/files/125450/Archivo.1.0B2.Crash.Log.02102016.txt)

**Comment by fflewddur** [comment]
Thanks for reporting this! First, what version of Java do you have installed? You should be able to check this by opening up Terminal (in Applications/Utilities folder) and entering the following command: 
`java -version`
It should print out something like `java version "1.8.0_71"`; as long as it's larger than 1.8_40, we should be fine. If it's not, you'll need to install the latest version of Java from http://java.com.

The second thing to try is running Archivo from Terminal, which will print out some debugging information  as it starts up. You can do this by entering the following command:
`/Applications/Archivo.app/Contents/MacOS/Archivo`
Please copy and paste any output into this bug report

**Comment by alienmeatsack** [comment]
Hi. Here's my info per your post...

It showed it was installed but I got an error when runnning the version command, downloaded and installed it again twice before I got it to give me this info:

> FinalWookie:~ ****$ java -version
> java version "1.8.0_73"
> Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
> Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

Running Archivo again to see what happens. 

Archivo now runs. So whatever was wrong with my Java install was fixed the launch error. You might need to add a catch in there to check for and report missing or corrupted Java on launch?

App now seems to launch OK. Just relaunched it OK. So that was the problem.

Anythnig I can do to help figure out why Java was broken or not cooperating with Archivo?

r

**Comment by alienmeatsack** [comment]
I've successfully archived several shows this morning, including 1 that the other app failed on repeatedly. You are my hero good sir. I'd love to contribute some $ if you had a place to do so for this project.  

Thanks again!

r

**Comment by fflewddur** [comment]
Awesome, glad to hear you got it working! I'm not sure what might have been happening with your Java install; Archivo uses a launcher that is supposed to check for a valid Java VM before launching, but it might not be able to catch this sort corruption; I'll look into that. Thanks for letting me know!

**Comment by alienmeatsack** [comment]
Let me know if I can help in any way with logs or similar with this Java issue! Thanks again :D
