### ISSUE TITLE
Hide Archivo actually displays Dialog Box

### ISSUE THREAD

**Issue by alienmeatsack** [fflewddur/archivo#52]
CMD-H or choosing Archivo -> Hide Archivo (CMD-H) brings up a dialog box as attached instead of actually hiding the app.

![monosnap 2016-02-11 09-09-46](https://cloud.githubusercontent.com/assets/8703414/12979878/58ae9e94-d09f-11e5-9c91-484a30ab3fee.jpg)

**Comment by fflewddur** [comment]
This behavior is working correctly as of 1.0.5, thanks for the bug report!
