### ISSUE TITLE
Latest release does not boot, Windows 10

### ISSUE THREAD

**Issue by Trailblazer5** [fflewddur/archivo#54]
I have Windows 10 and when I install, everything goes ok. Then, when I boot Archivo it boots into WinRar with Archivo.jar.  I am running Java 8.0._74.b02. Please help.

Thanks,

Ed

**Comment by fflewddur** [comment]
It sounds like you have WinRAR associated with .jar files instead of the Java VM. The instructions at https://www.youtube.com/watch?v=tUmfF5_S-P8&noredirect=1 should help you get this fixed.

**Comment by Trailblazer5** [comment]
Thank you,  I changed the association of .jar files and it worked.

 

Ed
