### ISSUE TITLE
Pixelization/macroblocking in archived videos

### ISSUE THREAD

**Issue by schenfeldt** [fflewddur/archivo#56]
Using Windows 10 and PrivateInternetAccess VPN, PC is unable to find TiVo device.  They are on the same network - disabling firewall for private connections didn't help.  If I disable the VPN it works fine.  Any ideas on how to use without disabling the VPN?

**Comment by fflewddur** [comment]
Some VPN configurations are not compatible with multicast DNS (also knows as Bonjour), which is how TiVos identify themselves on a network. Can you confirm that you're using the Layer 2 Tunneling Protocol  (L2TP) in your VPN setup? Other configurations will prevent the multicast packets from traveling between your computer and your TiVo (or any other Bonjour-compatible devices).

**Comment by schenfeldt** [comment]
Thanks Todd.  Turns out I could get around it by disabling the VPN for the first run – let it find the the Tivo- then turn it back on.  All is now good.

 

Except – 

 

Everything I convert has digital artifacts every few seconds – blocks of large pixels.  It runs clear for a few then a second of what looks like compression artifacts then back to good.  Source hasn’t mattered – I’ve tried several shows.  I’ve tried all settings too – 720p vs. 1040, no hardware compression, leave commercials intact.  Any ideas what to do?

**Comment by fflewddur** [comment]
@schenfeldt, it sounds like the files aren't decoding properly. Could you try the new 1.0.1 release (available at http://straylightlabs.net/archivo/#download) to see if that resolves the issue? If not, let me know and we'll figure out what's going wrong with the decoding process.

**Comment by schenfeldt** [comment]
Hi Todd – thanks for the note and new release, but the problem remains.  You have 1 second or two of perfect audio / video, then you have a few bars of pixelization (macroblocking).  It happens throughout the recording.  I’ve tried a few different shows – all the same problem.  Everything else is working perfectly – commercials are removed, etc.

**Comment by fflewddur** [comment]
Thanks @schenfeldt. One last thing to verify before I ask for a copy of one of the video files; what file type are you saving the recording as? If you haven't yet tried "Decrypted TiVo File", could you let me know if the problem also occurs with that filetype? That'll tell us whether the problem is with the decryption process (which it sounds like it is), or the conversion process to another video format.

**Comment by schenfeldt** [comment]
I tried a few more things – specifically archiving in three types :

 

-          H.264

-          H.264 high profile

-          Decrypted Tivo Files

 

All three have the same macroblocking problem.  Which would seem to indicate it’s the decryption, right?

 

 

From: Chris Schenfeldt [mailto:chris@objectdesigns.com] 
Sent: Thursday, April 14, 2016 8:56 AM
To: 'fflewddur/archivo' <reply@reply.github.com>; 'fflewddur/archivo' <archivo@noreply.github.com>
Subject: RE: [fflewddur/archivo] Unable to find Tivo (#56)

 

Hi Todd – thanks for the note and new release, but the problem remains.  You have 1 second or two of perfect audio / video, then you have a few bars of pixelization (macroblocking).  It happens throughout the recording.  I’ve tried a few different shows – all the same problem.  Everything else is working perfectly – commercials are removed, etc.

**Comment by fflewddur** [comment]
Yep, sounds like the problem is with the decoding. If you have the time, try saving one of these videos as an "Encrypted TiVo File". If you have the ability to upload it somewhere, do that and email me the link to download it, along with your MAK so I can debug the decryption process. If you don't have anywhere to upload a file this large, email me and I'll send you instructions for uploading it to my own server. My email is todd@dropline.net. Thanks!

**Comment by fflewddur** [comment]
@schenfeldt: Is this problem still occurring? If so, you might want to try the new 1.1 release, which fixes a number of bugs. The new version is available at https://straylightlabs.net/archivo/#download.

**Comment by schenfeldt** [comment]
No – all problems seem to be fixed with 1.1 release – thank you!  This means the discovery of the tivo when running VPN, the macroblocking during handbrake runs, and the stalls when running a batch archive of multiple shows.  Thank you for checking and your work on this project.

**Comment by fflewddur** [comment]
Awesome, thanks for testing it out!
