### ISSUE TITLE
ver 1.0 audio problem

### ISSUE THREAD

**Issue by Rik46** [fflewddur/archivo#57]
Audio Bug
Had no problem with audio in ver 1.0 beta 2 but the later release for ver. 1.0 has an audio problem.
After archiving many hours of programs with  #both versions, the latest version loses audio after about 30 minutes in any length program but the video continues to the end whether it is 1 hour or 3 hours.  The originals have full audio when played on a tivo bolt but when transfered with the later version 1.0 the audio gets lost.  Reinstalled back to the older ver. 1.0 beta 2 and the audio problem does not happen. Same computer i7 16 gig memory HP Notebook with Win 10.
also (feature suggestion)
the ability to select multiple files for deletion instead of having to remove them from the tivo manually from within archivo.
Otherwise your program is a Godsend. GREAT WORK and really appreciated!

**Comment by fflewddur** [comment]
Thanks for the report! I've put together a pre-release that should fix this; could you let me know if works for you? You can download the Windows version at https://dl.dropboxusercontent.com/u/41560798/Archivo%201.0.1.exe.

**Comment by mat1234** [comment]
Todd,

I had the same iss as Rik...  Loss of audio sync about 60% into the file.  I downloaded 1.0.1 that you provided and on my test show (30 minute show) it worked flawlessly.

Im going to queue up a bunch tonight.  Ill let you know tomorrow how it goes.  THANKS!

**Comment by mat1234** [comment]
I completed 20 TV shows using the 1.0.1 beta.  Some shows were 30 minutes, some 60 minutes.  All of them had the correct audio sync. I would say its fixed!

**Comment by fflewddur** [comment]
Awesome, thanks for letting me know!
