### ISSUE TITLE
Error on programs without commercials

### ISSUE THREAD

**Issue by fflewddur** [fflewddur/archivo#75]
ffmpeg exits with an error if it tries to remove commercials from a recording without any commercials. Relevant part of log file is:

21:05:24.088 [pool-3-thread-1] INFO  n.s.archivo.controller.ArchiveTask - splitList: FFSplitList{segmentsToKeep=[]}
21:05:24.088 [pool-3-thread-1] INFO  n.s.archivo.controller.ArchiveTask - Running command: tools\ffmpeg.exe -f concat -fflags +genpts+igndts -safe 0 -i D:\TivoTests\Bob's Burgers - S03E16 - Topsy.fixed.parts -codec copy D:\TivoTests\Bob's Burgers - S03E16 - Topsy.cut.ts
21:05:24.290 [pool-3-thread-1] ERROR n.s.archivo.controller.ArchiveTask - Error running command [tools\ffmpeg.exe, -f, concat, -fflags, +genpts+igndts, -safe, 0, -i, D:\TivoTests\Bob's Burgers - S03E16 - Topsy.fixed.parts, -codec, copy, D:\TivoTests\Bob's Burgers - S03E16 - Topsy.cut.ts]: exit code = 1
21:05:24.290 [pool-3-thread-1] ERROR n.s.archivo.controller.ArchiveTask - FFmpeg error: ffmpeg version 3.0.2-straylight-labs Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (Rev5, Built by MSYS2 project)
  configuration: --extra-version=straylight-labs --enable-asm --enable-yasm --enable-gpl --enable-version3 --disable-ffserver --disable-avdevice --disable-swscale --disable-doc --disable-ffplay --extra-ldflags=-static
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavfilter     6. 31.100 /  6. 31.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
D:\TivoTests\Bob's Burgers - S03E16 - Topsy.fixed.parts: Invalid data found when processing input

**Comment by AppleTechy** [comment]
Does Archive remove the commercials automatically?
